apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - name: kube-scheduler
    volumeMounts:
    - name: config
      mountPath: /var/lib/scheduler
      readOnly: true
  volumes:
  - hostPath:
      path: /var/lib/scheduler
      type: Directory
    name: config
