# ref: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
    groups:
      github-actions-updates:
        patterns:
          - "*"
    cooldown:
      default-days: 14
  - package-ecosystem: "gomod"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
    groups:
      gomod-dependencies-update:
        patterns:
          - "*"
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "github.com/prometheus/*"
      - dependency-name: "google.golang.org/grpc"
      - dependency-name: "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
      - dependency-name: "google.golang.org/protobuf"
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/client-go"
      - dependency-name: "k8s.io/mount-utils"
      - dependency-name: "sigs.k8s.io/controller-runtime"
      - dependency-name: "sigs.k8s.io/controller-tools"
