socket-name: /run/topolvm/lvmd.sock
device-classes:
  - name: ssd
    volume-group: myvg1
    default: true
    spare-gb: 10
    lvcreate-options:
      - --type
      - writecache
      - --cachesize
      - 10M
      - --cachedevice
      - CACHEDEVICE
  - name: ssd-thin
    volume-group: myvg1
    type: thin
    thin-pool:
      name: thinpool
      overprovision-ratio: 10.0
