kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: topolvm-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
  namespace: default
  labels:
    app.kubernetes.io/name: my-pod
    app: example
spec:
  containers:
  - name: ubuntu
    image: quay.io/cybozu/ubuntu:20.04
    command: ["/usr/local/bin/pause"]
    volumeMounts:
    - mountPath: /test1
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: topolvm-pvc2
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-ephemeral2
  namespace: default
  labels:
    app.kubernetes.io/name: my-pod-ephemeral
    app: example
spec:
  containers:
  - name: ubuntu
    image: quay.io/cybozu/ubuntu:20.04
    command: ["/usr/local/bin/pause"]
    volumeMounts:
    - mountPath: /test1
      name: my-volume
  volumes:
  - name: my-volume
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: topolvm-provisioner
