image:
  repository: topolvm
  tag: dev
  pullPolicy: Never

controller:
  replicaCount: 1
  securityContext:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: topolvm-e2e-worker
  # The nodeSelector above combined with the default podAntiAffinity means we
  # cannot use RollingUpdate.
  updateStrategy:
    type: Recreate
  # sanity test requires that the controller mounts this hostPath to communicate with it
  volumes:
    - name: socket-dir
      hostPath:
        path: /var/lib/kubelet/plugins/topolvm.cybozu.com/controller
        type: DirectoryOrCreate

scheduler:
  type: deployment
  deployment:
    replicaCount: 2
  service:
    type: NodePort
    nodePort: 30251
  options:
    listen:
      host: 0.0.0.0
  tolerations: null
  affinity: null

lvmd:
  managed: false

node:
  lvmdSocket: /tmp/topolvm/lvmd.sock

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        topolvm.cybozu.com/device-class: "ssd"

podSecurityPolicy:
  create: false

cert-manager:
  enabled: true
