FROM quay.io/cybozu/ubuntu-debug:18.04

COPY build/lvmetrics /lvmetrics
COPY build/topolvm-scheduler /topolvm-scheduler
COPY build/topolvm-hook /topolvm-hook
COPY build/csi-topolvm /csi-topolvm
COPY build/topolvm-node /topolvm-node
COPY build/lvmd-fake /lvmd
