kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v@KUBERNETES_VERSION@"
  networking:
    serviceSubnet: 10.0.0.0/16
  scheduler:
    extraVolumes:
      - name: "config"
        hostPath: /mnt/host/scheduler
        mountPath: /var/lib/scheduler
        readOnly: true
    extraArgs:
      config: /var/lib/scheduler/scheduler-config.yaml
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraMounts:
    - containerPath: /mnt/host/scheduler
      hostPath: /tmp/topolvm/scheduler
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/controller
      propagation: Bidirectional
# the three workers
- role: worker
  extraMounts:
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm/lvmd1
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker1
      propagation: Bidirectional
- role: worker
  extraMounts:
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm/lvmd2
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker2
      propagation: Bidirectional
- role: worker
  extraMounts:
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm/lvmd3
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker3
      propagation: Bidirectional
