{{- if and .Values.podSecurityPolicy.create .Values.lvmd.managed }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  privileged: true
  hostPID: true
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'hostPath'
    - 'secret'
  allowedHostPaths:
    {{- if .Values.lvmd.psp.allowedHostPaths }}
    {{- toYaml .Values.lvmd.psp.allowedHostPaths | nindent 4 }}
    {{- else }}
    - pathPrefix: {{ dir .Values.lvmd.socketName }}
      readOnly: false
    {{- end }}
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
{{- end }}
