name: "e2e-k8s"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-go
        with:
          go-version-file: "go.mod"
          takumi-guard-bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: cache e2e sidecar binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            test/e2e/tmpbin
          key: e2e-sidecars-${{ hashFiles('csi-sidecars.mk', 'versions.mk') }}
          restore-keys: |
            e2e-sidecars-
      - run: make -C test/e2e setup
      - run: make -C test/e2e topolvm.img
      - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            bin
            test/e2e/bin
            test/e2e/topolvm.img
          key: e2e-cache-${{ github.sha }}

  default:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    permissions:
      contents: read
      id-token: write
    with:
      test_scheduler_extender_type: "daemonset"
      test_legacy: false

  scheduler-manifest:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    permissions:
      contents: read
      id-token: write
    with:
      test_scheduler_extender_type: "deployment"
      test_legacy: false

  use-legacy:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    permissions:
      contents: read
      id-token: write
    with:
      test_scheduler_extender_type: "deployment"
      test_legacy: true

  storage-capacity-scoring:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    permissions:
      contents: read
      id-token: write
    with:
      test_scheduler_extender_type: "none"
      test_legacy: false
