name: "Lint Charts"

on:
  pull_request:
    paths:
      - "charts/**"
      - "ct.yaml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: "go.mod"

      - name: "Setup Tools"
        run: |
          make tools

      - name: "Run helm-docs"
        run: ./bin/helm-docs && git diff --no-patch --exit-code

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml
