name: meta

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

jobs:
  actionlint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-go
        with:
          go-version: stable
          takumi-guard-bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - run: make run-actionlint

  ghalint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-go
        with:
          go-version: stable
          takumi-guard-bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - run: make run-ghalint

  zizmor:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: make run-zizmor
